server:
  port: 8055
spring:
  application:
    name: fund

  data:
    mongodb:
      fund:
        uri: mongodb://127.0.0.1:27017/fund_data

ten-stock:
  list:
    - name: HK腾讯
      code: rt_hk00700
      holding-rate: 6.70
      isUSA: false
      dataSource: sina

    - name: TW台积电
      code: 103240
      holding-rate: 6.70
      isUSA: false
      dataSource: investing

    - name: HK阿里巴巴
      code: rt_hk09988
      holding-rate: 6.50
      isUSA: false
      dataSource: sina

    - name: 韩国三星电子
      code: 43433
      holdingRate: 6.3
      isUSA: false
      dataSource: investing

    - name: HK金山软件
      code: rt_hk03888
      holdingRate: 3.90
      isUSA: false
      dataSource: sina

    - name: Keyence Corp
      code: 943426
      holdingRate: 3.90
      isUSA: false
      dataSource: investing

    - name: SK Hynix INC
      code: 43430
      holdingRate: 3.90
      isUSA: false
      dataSource: investing

    - name: GDS Holdings Ltd
      code: gb_gds
      holdingRate: 3.80
      isUSA: true
      dataSource: sina

    - name: USA SeaLimited
      code: gb_se
      holdingRate: 3.70
      isUSA: true
      dataSource: sina

    - name: HK金蝶国际
      code: rt_hk00268
      holdingRate: 3.70
      isUSA: false
      dataSource: sina